CREATE TABLE IF NOT EXISTS public.rmac_activities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  reference_code text NOT NULL UNIQUE,
  org_slug text NOT NULL,
  village_slug text NOT NULL DEFAULT 'alofi-south',
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  activity_date date NOT NULL,
  action_area text NOT NULL CHECK (
    action_area IN (
      'marine',
      'fish',
      'culture',
      'pollution',
      'tourism',
      'legal',
      'climate',
      'capacity',
      'other'
    )
  ),
  description text NOT NULL CHECK (char_length(description) BETWEEN 20 AND 2000),
  people_count integer CHECK (people_count IS NULL OR people_count BETWEEN 0 AND 10000),
  people_notes text CHECK (people_notes IS NULL OR char_length(people_notes) <= 500),
  spend_nzd numeric(12, 2) CHECK (spend_nzd IS NULL OR spend_nzd BETWEEN 0 AND 10000000),
  latitude numeric(9, 6) CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
  longitude numeric(9, 6) CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
  location_name text CHECK (location_name IS NULL OR char_length(location_name) <= 200),
  location_accuracy_m numeric(10, 2) CHECK (
    location_accuracy_m IS NULL OR location_accuracy_m BETWEEN 0 AND 100000
  ),
  visibility text NOT NULL DEFAULT 'committee'
    CHECK (visibility IN ('committee', 'approved_reporting')),
  photo_consent_confirmed boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'returned')),
  review_notes text CHECK (review_notes IS NULL OR char_length(review_notes) <= 1000),
  submitted_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS rmac_activities_org_status_idx
  ON public.rmac_activities (org_slug, status, activity_date DESC);
CREATE INDEX IF NOT EXISTS rmac_activities_created_by_idx
  ON public.rmac_activities (created_by, created_at DESC);
CREATE INDEX IF NOT EXISTS rmac_activities_reviewed_by_idx
  ON public.rmac_activities (reviewed_by);

CREATE TABLE IF NOT EXISTS public.rmac_activity_evidence (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  activity_id uuid NOT NULL REFERENCES public.rmac_activities(id) ON DELETE CASCADE,
  storage_path text NOT NULL UNIQUE,
  original_name text NOT NULL,
  mime_type text NOT NULL CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/webp')),
  size_bytes integer NOT NULL CHECK (size_bytes BETWEEN 1 AND 10485760),
  created_by uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS rmac_activity_evidence_activity_idx
  ON public.rmac_activity_evidence (activity_id, created_at);
CREATE INDEX IF NOT EXISTS rmac_activity_evidence_created_by_idx
  ON public.rmac_activity_evidence (created_by);

CREATE TABLE IF NOT EXISTS public.rmac_activity_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activity_id uuid NOT NULL REFERENCES public.rmac_activities(id) ON DELETE CASCADE,
  actor_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  action text NOT NULL CHECK (action IN ('submitted', 'resubmitted', 'approved', 'returned')),
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS rmac_activity_audit_activity_idx
  ON public.rmac_activity_audit (activity_id, created_at);
CREATE INDEX IF NOT EXISTS rmac_activity_audit_actor_idx
  ON public.rmac_activity_audit (actor_id);

ALTER TABLE public.rmac_activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rmac_activity_evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rmac_activity_audit ENABLE ROW LEVEL SECURITY;

REVOKE INSERT, UPDATE, DELETE ON public.rmac_activities FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.rmac_activity_evidence FROM anon, authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.rmac_activity_audit FROM anon, authenticated;

CREATE POLICY "rmac_org_members_read_activities"
  ON public.rmac_activities FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND p.invite_status = 'active'
        AND (p.org_slug = rmac_activities.org_slug OR p.role = 'deqode_admin')
    )
  );

CREATE POLICY "rmac_members_submit_activities"
  ON public.rmac_activities FOR INSERT
  TO authenticated
  WITH CHECK (
    created_by = (SELECT auth.uid())
    AND EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND p.invite_status = 'active'
        AND p.org_slug = rmac_activities.org_slug
    )
  );

CREATE POLICY "rmac_reviewers_update_activities"
  ON public.rmac_activities FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND p.invite_status = 'active'
        AND p.role IN ('analyst', 'admin', 'deqode_admin')
        AND (p.org_slug = rmac_activities.org_slug OR p.role = 'deqode_admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND p.invite_status = 'active'
        AND p.role IN ('analyst', 'admin', 'deqode_admin')
        AND (p.org_slug = rmac_activities.org_slug OR p.role = 'deqode_admin')
    )
  );

CREATE POLICY "rmac_org_members_read_evidence"
  ON public.rmac_activity_evidence FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.rmac_activities a
      JOIN public.profiles p ON p.id = (SELECT auth.uid())
      WHERE a.id = rmac_activity_evidence.activity_id
        AND p.invite_status = 'active'
        AND (p.org_slug = a.org_slug OR p.role = 'deqode_admin')
    )
  );

CREATE POLICY "rmac_members_add_evidence"
  ON public.rmac_activity_evidence FOR INSERT
  TO authenticated
  WITH CHECK (
    created_by = (SELECT auth.uid())
    AND EXISTS (
      SELECT 1
      FROM public.rmac_activities a
      JOIN public.profiles p ON p.id = (SELECT auth.uid())
      WHERE a.id = rmac_activity_evidence.activity_id
        AND a.created_by = (SELECT auth.uid())
        AND p.invite_status = 'active'
        AND p.org_slug = a.org_slug
    )
  );

CREATE POLICY "rmac_org_members_read_audit"
  ON public.rmac_activity_audit FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM public.rmac_activities a
      JOIN public.profiles p ON p.id = (SELECT auth.uid())
      WHERE a.id = rmac_activity_audit.activity_id
        AND p.invite_status = 'active'
        AND (p.org_slug = a.org_slug OR p.role = 'deqode_admin')
    )
  );

CREATE OR REPLACE FUNCTION public.set_rmac_activity_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS rmac_activity_updated_at ON public.rmac_activities;
CREATE TRIGGER rmac_activity_updated_at
  BEFORE UPDATE ON public.rmac_activities
  FOR EACH ROW EXECUTE FUNCTION public.set_rmac_activity_updated_at();

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'rmac-evidence',
  'rmac-evidence',
  false,
  10485760,
  ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO UPDATE
SET public = false,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

CREATE POLICY "rmac_members_read_storage"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'rmac-evidence'
    AND EXISTS (
      SELECT 1
      FROM public.profiles p
      WHERE p.id = (SELECT auth.uid())
        AND p.invite_status = 'active'
        AND (p.org_slug = (storage.foldername(name))[1] OR p.role = 'deqode_admin')
    )
  );
